version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mrtsolarcongonhas-frontend
    networks:
      - proxy

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mrtsolarcongonhas-backend
    env_file:
      - .env
    ports:
      - "3040:3040"
    networks:
      - proxy

networks:
    proxy:
        external: true
