# /nginx.conf
server {
  # O servidor vai escutar na porta 80
  listen 80;

  # Define a raiz onde os arquivos do seu site estão
  root /usr/share/nginx/html;

  # Garante que o Nginx procure por index.html como página padrão
  index index.html;

  # Configuração principal para SPAs (Single-Page Applications)
  location / {
    # Tenta encontrar o arquivo exato solicitado pelo navegador
    # Se não encontrar, tenta encontrar uma pasta com esse nome
    # Se falhar em ambos, ele redireciona a requisição para /index.html
    # Isso permite que o Vue Router controle a navegação no lado do cliente.
    try_files $uri $uri/ /index.html;
  }
}